// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDz8Pvhqzh2p6JZV5tfoVkmIxp9DDFog',
    appId: '1:877463268797:web:ceeceaa8861944c514b6d4',
    messagingSenderId: '877463268797',
    projectId: 'resume-analyzer-97015',
    authDomain: 'resume-analyzer-97015.firebaseapp.com',
    storageBucket: 'resume-analyzer-97015.firebasestorage.app',
    measurementId: 'G-QVMRV584W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNLoc0CcI4hR7msWkp3-0MFWc_dvKmjo',
    appId: '1:877463268797:android:8b32b81c5b30e65414b6d4',
    messagingSenderId: '877463268797',
    projectId: 'resume-analyzer-97015',
    storageBucket: 'resume-analyzer-97015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaoN-RlVvi4QUSI9uycqge5uszZJHXdyo',
    appId: '1:877463268797:ios:2a0ba3d4836e3fb714b6d4',
    messagingSenderId: '877463268797',
    projectId: 'resume-analyzer-97015',
    storageBucket: 'resume-analyzer-97015.firebasestorage.app',
    iosBundleId: 'com.example.resumeAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaoN-RlVvi4QUSI9uycqge5uszZJHXdyo',
    appId: '1:877463268797:ios:2a0ba3d4836e3fb714b6d4',
    messagingSenderId: '877463268797',
    projectId: 'resume-analyzer-97015',
    storageBucket: 'resume-analyzer-97015.firebasestorage.app',
    iosBundleId: 'com.example.resumeAnalyzer',
  );
}
